[package]
name = "quakk_cli"
description.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "quakk_cli"
path = "src/main.rs"

[dependencies]
quakk.workspace = true
quakk_numeric.workspace = true

anyhow.workspace = true
