[package]
name = "quack_sth_cli"
description.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "quack_sth_cli"
path = "src/main.rs"

[dependencies]
quack_sth.workspace = true
numeric.workspace = true

anyhow.workspace = true
